# Generated by Django 3.0.3 on 2020-02-26 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='degree',
            new_name='course',
        ),
    ]
